### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jarthorn** [diervo/html5rubik#1]
Have played with the demo on your blog, this is really cool! I would like to check out the source but don't see a license. Can you add a license file to indicate what OSS license you are using for this code?

**Comment by diervo** [comment]
Feel free to use the code however you like, I will add the license whenever
I can.

2014-12-23 13:19 GMT-08:00 John Arthorne notifications@github.com:

> Have played with the demo on your blog, this is really cool! I would like
> to check out the source but don't see a license. Can you add a license file
> to indicate what OSS license you are using for this code?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/diervo/html5rubik/issues/1.

## 

Diego Ferreiro Val
@diervo
